/**************************************************************************/
/* main.cpp                                                               */
/**************************************************************************/
/*                          This file is part of:                         */
/*                              SushiEngine                               */
/*               https://github.com/SushiSystems/SushiEngine              */
/*                        https://sushisystems.io                         */
/**************************************************************************/
/* Copyright (c) 2026-present Mustafa Garip & Sushi Systems               */
/*                                                                        */
/* Licensed under the Apache License, Version 2.0 (the "License");        */
/* you may not use this file except in compliance with the License.       */
/* You may obtain a copy of the License at                                */
/*                                                                        */
/*     http://www.apache.org/licenses/LICENSE-2.0                         */
/*                                                                        */
/* Unless required by applicable law or agreed to in writing, software    */
/* distributed under the License is distributed on an "AS IS" BASIS,      */
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or        */
/* implied. See the License for the specific language governing           */
/* permissions and limitations under the License.                         */
/**************************************************************************/

// Build-time host tool: compiles one GLSL shader to SPIR-V with glslang and emits a
// C++ header holding the words as an inline constexpr array. CMake runs it per
// shader (see sushi_compile_shader), so the shipped renderer embeds SPIR-V and
// carries no runtime shader-compiler dependency. This tool is never installed and
// never linked into the renderer — it only runs during the build.
//
// usage: shader_compiler <vert|frag> <input.glsl> <output.h> <symbol_name>

#include <cstdint>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include <glslang/Public/ResourceLimits.h>
#include <glslang/Public/ShaderLang.h>
#include <glslang/SPIRV/GlslangToSpv.h>

namespace
{
    /**
     * @brief Reads a whole text file into a string.
     * @param path File to read.
     * @param out  Receives the file contents on success.
     * @return true if the file was opened and read.
     */
    bool read_file(const char* path, std::string& out)
    {
        std::ifstream stream(path, std::ios::binary);
        if (!stream)
            return false;
        std::ostringstream buffer;
        buffer << stream.rdbuf();
        out = buffer.str();
        return true;
    }

    /**
     * @brief Writes the SPIR-V words as an inline constexpr C++ array header.
     * @param path   Output header path.
     * @param symbol Array symbol name (namespaced under SushiEngine::Render::Shaders).
     * @param words  The compiled SPIR-V words.
     * @return true on success.
     */
    bool write_header(const char* path, const std::string& symbol,
                      const std::vector<std::uint32_t>& words)
    {
        std::ofstream out(path, std::ios::binary);
        if (!out)
            return false;

        out << "// Generated by shader_compiler. Do not edit.\n";
        out << "#pragma once\n#include <cstddef>\n#include <cstdint>\n\n";
        out << "namespace SushiEngine { namespace Render { namespace Shaders {\n";
        out << "inline constexpr std::uint32_t " << symbol << "[] = {\n";
        for (std::size_t i = 0; i < words.size(); ++i)
        {
            if (i % 8 == 0)
                out << "    ";
            char hex[16];
            std::snprintf(hex, sizeof(hex), "0x%08x,", words[i]);
            out << hex << ((i % 8 == 7) ? "\n" : " ");
        }
        out << "\n};\ninline constexpr std::size_t " << symbol << "_word_count = "
            << words.size() << ";\n";
        out << "}}} // namespace SushiEngine::Render::Shaders\n";
        return true;
    }
}

int main(int argc, char** argv)
{
    if (argc != 5)
    {
        std::fprintf(stderr,
                     "usage: %s <vert|frag> <input.glsl> <output.h> <symbol_name>\n",
                     argv[0]);
        return 2;
    }

    const std::string stage_name = argv[1];
    const char* input_path = argv[2];
    const char* output_path = argv[3];
    const std::string symbol = argv[4];

    EShLanguage stage;
    if (stage_name == "vert")
        stage = EShLangVertex;
    else if (stage_name == "frag")
        stage = EShLangFragment;
    else
    {
        std::fprintf(stderr, "shader_compiler: unknown stage '%s'\n", stage_name.c_str());
        return 2;
    }

    std::string source;
    if (!read_file(input_path, source))
    {
        std::fprintf(stderr, "shader_compiler: cannot read '%s'\n", input_path);
        return 1;
    }

    glslang::InitializeProcess();

    glslang::TShader shader(stage);
    const char* source_ptr = source.c_str();
    shader.setStrings(&source_ptr, 1);
    shader.setEnvInput(glslang::EShSourceGlsl, stage, glslang::EShClientVulkan, 100);
    shader.setEnvClient(glslang::EShClientVulkan, glslang::EShTargetVulkan_1_3);
    shader.setEnvTarget(glslang::EShTargetSpv, glslang::EShTargetSpv_1_6);

    const int default_version = 100;
    const EShMessages messages =
        static_cast<EShMessages>(EShMsgSpvRules | EShMsgVulkanRules);

    if (!shader.parse(GetDefaultResources(), default_version, false, messages))
    {
        std::fprintf(stderr, "shader_compiler: parse failed for '%s':\n%s\n%s\n",
                     input_path, shader.getInfoLog(), shader.getInfoDebugLog());
        glslang::FinalizeProcess();
        return 1;
    }

    glslang::TProgram program;
    program.addShader(&shader);
    if (!program.link(messages))
    {
        std::fprintf(stderr, "shader_compiler: link failed for '%s':\n%s\n",
                     input_path, program.getInfoLog());
        glslang::FinalizeProcess();
        return 1;
    }

    std::vector<std::uint32_t> spirv;
    glslang::GlslangToSpv(*program.getIntermediate(stage), spirv);
    glslang::FinalizeProcess();

    if (!write_header(output_path, symbol, spirv))
    {
        std::fprintf(stderr, "shader_compiler: cannot write '%s'\n", output_path);
        return 1;
    }
    return 0;
}
